@startuml
'https://plantuml.com/sequence-diagram

autonumber
@startuml
actor employee as employee
participant       .jsp       as jsp
control     FrontController as fc
entity     Command         as cmd
control      Facade         as face
participant    Mapper            as map
database Database           as dat

employee -> jsp : Press link to bomPage.jsp
jsp -> fc : Find "bomPage"
fc -> cmd : bomCommand.execute()
cmd -> face : bomFacade.getOrderlineMaterials()
face -> map : bomMapper.getOrderlineMaterials()
map -> dat : executeQuery()
dat -> cmd : Retrieve ResultSet
cmd -> fc : pageToShow
fc -> jsp : bomPage.jsp
jsp -> employee : Show page

@enduml
@enduml