@startuml
'https://plantuml.com/sequence-diagram

autonumber
@startuml
actor customer as customer
participant       .jsp       as jsp
control     FrontController as fc
entity     Command         as cmd
control      Facade         as face
participant    Mapper            as map
database Database           as dat

customer -> jsp : Press link to customCarport.jsp
jsp -> fc : Find "customCarport"
fc -> cmd : CustomCarportCommand.execute()
cmd -> fc : pageToShow
fc -> jsp : customCarport.jsp
jsp -> customer : Show page
customer -> jsp : Choose measurements

jsp -> fc : Find "requestReceivedPage"
fc -> cmd : CustomCarportCommand.execute()
cmd -> fc : pageToShow
fc -> jsp : requestConfirmedPage.jsp
jsp -> customer : Show page
customer -> jsp : Confirm measures
jsp -> fc : Find "requestConfirmedPage"
fc -> cmd : ConfirmRequestCommand.execute()

cmd -> face : OrderFacade.addOrderToDatabase()
face -> map : OrderMapper.addOrderToDatabase()
map -> dat : execute()
cmd -> face : OrderFacade.getLatestOrderIdFromUserId()
face -> map : OrderMapper.getLatestOrderIdFromUserId()
map -> dat : executeQuery()
dat -> cmd : Retrieve latest OrderID
cmd -> face : BomFacade.generateCarport()
face -> map : BomFacade.generateCarport()
map -> dat : execute()
cmd -> fc : pageToShow
fc -> jsp : RequestConfirmedPage.jsp
jsp -> customer : Show page
@enduml
@enduml