@startuml
'https://plantuml.com/sequence-diagram

autonumber
@startuml
actor participant as Foo

participant     Frontcontroler      as Foo2
participant      facade      as Foo3
participant    mapper    as Foo4
database database as Foo5

Foo -> Foo2 : Start application
Foo2 -> Foo3 : Calling CarportFacade
Foo3 -> Foo4 : getMeasureEntities() & getStandardCarportEntitiesList
Foo4 -> Foo5 : retrieve measures & standard entities
Foo5 -> Foo2 : List<MeasureEntities> & List<StandardCarportEntity>

@enduml